services:
  mysql:
    container_name: winx_mysql
    platform: linux/x86_64
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    env_file:
      - ./db/local.env
    tty: true
  api:
    depends_on:
      - mysql
    container_name: winx_api
    platform: linux/x86_64
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    env_file:
      - ./app/local.env
volumes:
    mysql_data:
